### PR TITLE
added all SMD inductors from other libs + fixed all KLC issues

### PR DESCRIPTION
**Pull request by jkriege2**
OK, these should be all SMD-inductors from 
- Air_Coils_SML_NEOSID.pretty
- Choke_SMD.pretty
- Inductors.pretty
- Inductors_NEOSID.pretty

Hope I didn't miss any ;-)

### CODE REVIEW

**Comment by SchrodingersGat** [comment]
@jkriege2 why closed? I was just about to merge it :)

**Comment by jkriege2** [comment]
was too quick ... I added more, so I'll push it later again with all SMD-inductors ... those were only the Neosid-ones

**Comment by SchrodingersGat** [comment]
Let's keep the merge PRs separate! Easier to deal with

e.g. I have done the ones from Inductors.pretty

https://github.com/KiCad/Inductors_SMD.pretty/pull/2

**Comment by jkriege2** [comment]
Ahhh ... OK was just doing the same ... I put in some work to fix several KLC-issues and add missing F.Fab ... So which one should we take?

**Comment by jkriege2** [comment]
PS: I'll now prepare a PR for kicad-library that renames all 3D models appropriately!

**Comment by jkriege2** [comment]
Hi!

here's the 3D packages PR: https://github.com/KiCad/kicad-library/pull/923

**Comment by SchrodingersGat** [comment]
@jkriege2 thanks for that :) feel free to tackle the rest of the "old" .pretty repos - I'm off to bed! :)

**Comment by SchrodingersGat** [comment]
I'll check these footprints soon, too.

**Comment by jkriege2** [comment]
Will do ... sleep well ;-)

Best,
JAN

**Comment by jkriege2** [comment]
OK!

I did the same now for the THT inductors: There's one PR for the old footprints + 3 split ones for new footprints (sorted by type). For each one there's a PR with 3D models ... Could you review/mergem them too?

best,
JAN

**Comment by SchrodingersGat** [comment]
Thanks @jkriege2 I'll merge this for now - we will have to move the Transformer footprints across to the new libs though.

**Pull request merged**
