### PR TITLE
Added Sagami CER1242B inductor

### PR DESCRIPTION
**Pull request by crackerizer**

### CODE REVIEW

**Comment by SchrodingersGat** [comment]
Hi @crackerizer thanks for the desire to contribute.

Firstly, check out the [Kicad Library Utils scripts](https://github.com/KiCad/kicad-library-utils) which can automatically help your footprint to meet the [KLC](https://github.com/KiCad/kicad-library/wiki/Kicad-Library-Convention).

Running this footprint through the script produces the following:

```
checking module: L_Sagami_CER1242B
  Violating Rule 10.5
    Reference designator has a height of 1mm or smaller if needed, thickness of 0.15mm and is placed on
    the silkscreen and the fabrication layer.
      Reference label should also be available on layer 'F.Fab'.
      
  Violating Rule 1.8
    Library files should use UNIX-style line-endings (LF)
  Violating Rule 6.5
    Silkscreen is not superposed to pads, its outline is completely visible after board assembly, uses
    0.12mm line width and provides a reference mark for pin 1. (IPC-7351C).
      Some silkscreen line has a width of 0.15mm, different from 0.12mm (line: {'width': 0.15, 'layer':
      'F.SilkS', 'start': {'y': -2.032, 'x': -3.81}, 'end': {'y': -2.032, 'x': -4.318}}).
      Some silkscreen line has a width of 0.15mm, different from 0.12mm (line: {'width': 0.15, 'layer':
      'F.SilkS', 'start': {'y': -2.032, 'x': 3.81}, 'end': {'y': -2.032, 'x': 4.318}}).
      Some silkscreen line has a width of 0.15mm, different from 0.12mm (line: {'width': 0.15, 'layer':
      'F.SilkS', 'start': {'y': 2.032, 'x': 3.81}, 'end': {'y': 2.032, 'x': 4.318}}).
      Some silkscreen line has a width of 0.15mm, different from 0.12mm (line: {'width': 0.15, 'layer':
      'F.SilkS', 'start': {'y': 2.032, 'x': -3.81}, 'end': {'y': 2.032, 'x': -4.318}}).
      Some silkscreen line has a width of 0.15mm, different from 0.12mm (line: {'width': 0.15, 'layer':
      'F.SilkS', 'start': {'y': 1.994, 'x': 6.29}, 'end': {'y': 6.5, 'x': 1.6}}).
      Some silkscreen line has a width of 0.15mm, different from 0.12mm (line: {'width': 0.15, 'layer':
      'F.SilkS', 'start': {'y': 1.994, 'x': -6.29}, 'end': {'y': 6.5, 'x': -1.6}}).
      Some silkscreen line has a width of 0.15mm, different from 0.12mm (line: {'width': 0.15, 'layer':
      'F.SilkS', 'start': {'y': -6.5, 'x': 1.6}, 'end': {'y': -1.994, 'x': 6.29}}).
      Some silkscreen line has a width of 0.15mm, different from 0.12mm (line: {'width': 0.15, 'layer':
      'F.SilkS', 'start': {'y': -6.5, 'x': -1.6}, 'end': {'y': -1.994, 'x': -6.29}}).
      Some silkscreen line has a width of 0.15mm, different from 0.12mm (line: {'width': 0.15, 'layer':
      'F.SilkS', 'start': {'y': 6.5, 'x': -1.6}, 'end': {'y': 6.5, 'x': 1.6}}).
      Some silkscreen line has a width of 0.15mm, different from 0.12mm (line: {'width': 0.15, 'layer':
      'F.SilkS', 'start': {'y': -6.5, 'x': -1.6}, 'end': {'y': -6.5, 'x': 1.6}}).
      Some silkscreen line has a width of 0.15mm, different from 0.12mm (line: {'width': 0.15, 'angle':
      90, 'layer': 'F.SilkS', 'start': {'y': 0, 'x': 0}, 'end': {'y': 2.032, 'x': 4.318}}).
      Some silkscreen line has a width of 0.15mm, different from 0.12mm (line: {'width': 0.15, 'angle':
      90, 'layer': 'F.SilkS', 'start': {'y': 0, 'x': 0}, 'end': {'y': 4.318, 'x': 2.032}}).
      Some silkscreen line has a width of 0.15mm, different from 0.12mm (line: {'width': 0.15, 'angle':
      90, 'layer': 'F.SilkS', 'start': {'y': 0, 'x': 0}, 'end': {'y': -4.318, 'x': -2.032}}).
      Some silkscreen line has a width of 0.15mm, different from 0.12mm (line: {'width': 0.15, 'angle':
      90, 'layer': 'F.SilkS', 'start': {'y': 0, 'x': 0}, 'end': {'y': -2.032, 'x': -4.318}}).
      Some silkscreen line has a width of 0.15mm, different from 0.12mm (line: {'width': 0.15, 'angle':
      90, 'layer': 'F.SilkS', 'start': {'y': 0, 'x': 0}, 'end': {'y': 2.032, 'x': 3.81}}).
      Some silkscreen line has a width of 0.15mm, different from 0.12mm (line: {'width': 0.15, 'angle':
      90, 'layer': 'F.SilkS', 'start': {'y': 0, 'x': 0}, 'end': {'y': 3.81, 'x': 2.032}}).
      Some silkscreen line has a width of 0.15mm, different from 0.12mm (line: {'width': 0.15, 'angle':
      90, 'layer': 'F.SilkS', 'start': {'y': 0, 'x': 0}, 'end': {'y': -3.81, 'x': -2.032}}).
      Some silkscreen line has a width of 0.15mm, different from 0.12mm (line: {'width': 0.15, 'angle':
      90, 'layer': 'F.SilkS', 'start': {'y': 0, 'x': 0}, 'end': {'y': -2.032, 'x': -3.81}}).
      
  Violating Rule 6.6
    Courtyard line has a width 0.05mm. This line is placed so that its clearance is measured from its
    center to the edges of pads and body, and its position is rounded on a grid of 0.01mm.
      A courtyard clearance in the range 0.15...0.35mm was found, but 0.25mm was expected.
      The recommendet courtyard rectangle would be:
          {'width': 16.3, 'y': -6.75, 'x': -8.15, 'height': 13.5}mm.
  Violating Rule 6.9
    Fabrication layer contains an outline of the part using a 0.1mm line width.
      No drawings found on fabrication layer at all.
      
```

Have a look at how the footprints in this library are formatted, with the outline placed on the F.Fab layer, etc.

A few tweaks and you should be ok. Let me know if there is anything in the script output above that is not clear.

**Comment by crackerizer** [comment]
@SchrodingersGat,

I did run the check script. There is no violation found. Did I miss any special parameter to pass to the script?

**Comment by crackerizer** [comment]
Here is the output:

checking module: L_Sagami_CER1242B
  No violations found

**Comment by SchrodingersGat** [comment]
Do you have the most up-to-date version of the scripts?

**Comment by SchrodingersGat** [comment]
Here's what I get:

untitled

**Comment by jkriege2** [comment]
A side note: run with `-v` for more verbose Output ... so you get an Explanation what the rules really mean and what breaks them!

JAN

**Comment by crackerizer** [comment]
Hi, I just updated script to the latest. However, I can not fix the rule 10.5 and --fix does not work. Any suggestion?

**Comment by SchrodingersGat** [comment]
Ah yes the documentation could be improved for 10.5

Please add a copy of the Refdes to the F.Fab layer. To do this, add a text object on the F.Fab layer, with the text `%R`.

**Comment by crackerizer** [comment]
Thank you so much, and I committed the fix.

**Comment by SchrodingersGat** [comment]
Thanks for the good work :)

**Pull request merged**
