### PR TITLE
Missing reference designators added

### PR DESCRIPTION
**Pull request by alitekin2fx**

### CODE REVIEW

**Comment by Shackmeister** [comment]
Can you please remove all the footprints which only has the timestamp changed from the PR? :)

**Comment by alitekin2fx** [comment]
Oh okay, committed the changes again.

**Comment by Shackmeister** [comment]
@aliteke79 Hi I have had a look at your branch and it looks nice. If you are up for it I have a few improvements:
L_0201, L_0402, Inductors_SMD:L_Wuerth_MAPI-1610, Inductors_SMD:L_Wuerth_MAPI-2010, Inductors_SMD:L_Wuerth_MAPI-4020: shrink refdes text size to fit inside fab line (0.1mm textsize is allowed according to KLC).

L_CommonMode_Wuerth_WE-SL2, L_Sagami_CER1242B, L_Sagami_CER1257B, Inductors_SMD:L_Sagami_CER1277B: move refdes to 0,0

L_Neosid_Ms50 and L_Neosid_Ms50: rotate refdes 90 degrees to fit better in the fab body

**Comment by alitekin2fx** [comment]
Hi @Shackmeister, i have fixed all except L_0201. Travis doesn't let me for thickness less then 0.1mm, so i moved the designator outside of rectangle region.

**Comment by Shackmeister** [comment]
hi @aliteke79 a few thing I noticed in the new updates
text thickness should be 15% of text width/height.. I think it slipped on L_0201
otherwise I think it looks good :)

There is a weird silkscreen line in L_Sagami_CWR1242C, L_Sagami_CWR1257C & L_Sagami_CWR1277C. I dont see why it should be there. perhaps @jkriege2 or @poeschlr would know. otherwise I think it should be removed
inductor

**Comment by evanshultz** [comment]
@Shackmeister 
I did it. You can see my PR at https://github.com/KiCad/Inductors_SMD.pretty/pull/13, and the original PR at https://github.com/KiCad/Inductors_SMD.pretty/pull/10#event-1137251147. This silk was discussed and accepted by Oliver. As you can read, the part is "polarized" and so the silk is to indicate proper component placement during installation. OK to merge.

Seeing it now, having something on F.Fab would have been good if I'd thought about it at the time.

**Comment by alitekin2fx** [comment]
Hi @Shackmeister, anything i need to do?

**Comment by poeschlr** [comment]
I think the polarization marker should move outside the part. For SMD parts there should not be any silk below the part because it can create problems while reflow soldering. (Having the polarization mark outside would also mean one can check the correct placement after assembly.)

Edit: Maybe a small circle at the corner nearest to both pads with number 1?

If a polarization mark is necessary on silk, there should also be one on the fab layer.

**Comment by Shackmeister** [comment]
@aliteke79 if you can fix the text thickness on L_0201 I think it's fine :) unless we should cover the polarization while we are at it

**Comment by alitekin2fx** [comment]
I looks much better when i set the thickness to 0,127 mm. But when i do that Travis refuses commit.
untitled

**Comment by Shackmeister** [comment]
@aliteke79 Text thickness on Fab layer should be allowed all the way down to 0.01 :/ Ill have a look at Travis if he's the one complaining

EDIT: https://github.com/KiCad/kicad-library-utils/blob/master/pcb/rules/klc_constants.py
looking here Travis allows 0.025mm text thickness so this shouldnt be a problem :/

**Comment by Shackmeister** [comment]
@aliteke79 can you try to upload the changes? we can merge it even if Travis disagrees, it will be fixed later

**Comment by alitekin2fx** [comment]
Hi @Shackmeister, you are right i have uploaded it with 0.025mm thickness.

**Comment by Shackmeister** [comment]
@aliteke79 looks good :) Ill merge this now. in case you would like to fix the polarity indication it could be really nice :) please open a new PR if you would like so

Thank you for your contribution! :D

**Pull request merged**
