### PR TITLE
Add 1806 SMD ferrite beads

### PR DESCRIPTION
**Pull request by evanshultz**
Image:
image

See page 100 (file page 102) of http://www.murata.com/~/media/webrenewal/support/library/catalog/products/emc/emifil/c31e.ashx?la=en-us.

### CODE REVIEW

**Comment by SchrodingersGat** [comment]
@evanshultz I am closing this only to re-open it so that the KLC rules auto-check :)

**Comment by evanshultz** [comment]
Weird. I don't see those Travis failures when I run locally or when I look at the file. Try again...

@SchrodingersGat I also found the description for the other SMT ferrite beads but 0201 seems to be remnants from the original seed files which were resistors. Right?

**Comment by SchrodingersGat** [comment]
KLC1.x scripts seem to still have a few bugs I'm afraid.

Please add extra refdes "%R" to F.Fab layer @ (0,0) :)

**Comment by evanshultz** [comment]
@SchrodingersGat Thank you. Done.

KLC 2.0 shows the courtyard on a grid of 0.01mm but I feel like it used to be 0.1mm. Leaving on 0.1mm grid for now. The other violations aren't real.

Lastly, I saw a typo in the Travis output of "recommended" when talking about the courtyard clearance it wanted me to have. It was spelled "recommendet". Now it's gone above and I can't find this text string in the check scripts.

**Comment by evanshultz** [comment]
Here's the typo I mentioned above:
image

**Comment by SchrodingersGat** [comment]
Thanks :)

**Pull request merged**
