### PR TITLE
Added Vishay IHLP inductors

### PR DESCRIPTION
**Pull request by SchrodingersGat**

### CODE REVIEW

**Comment by jkriege2** [comment]
Hi @SchrodingersGat 
Is there a reason why I don't have write-access to this Repo? I think this is the case for all other new repos too ...

Best
JAN

**Comment by SchrodingersGat** [comment]
@jkriege2 check now - I have reconfigured the permissions.

**Comment by jkriege2** [comment]
Hi!

yes it now works ... The footprints look good, except for the linewidths,
please change F.Fab to 0.1mm and F.SilkS to 0.12mm

Best,
JAN

**Comment by SchrodingersGat** [comment]
Done :)

**Comment by jkriege2** [comment]
Nice!

Thanks,
JAN

**Pull request merged**
