### PR TITLE
Add L_Wuerth_WE-SL2

### PR DESCRIPTION
**Pull request by MHolzbrecher**

### CODE REVIEW

**Comment by jkriege2** [comment]
Hi !

nice work so far ... Please make some smaller changes:
1. The outline on F.Fab should be closed, it does not have to keep away from pads!
2. add pin1-mark on F.SilkS
3. maybe add datasheet link to description
4. The name should start with `L_CommonMode_` ... see https://github.com/KiCad/Inductors_THT.pretty

Best,
JAN

**Comment by MHolzbrecher** [comment]
Hi, 
i modified and renamed it. Link to datasheet added. 

Michael

**Comment by jkriege2** [comment]
Hi1

mostly good now ... I pointed out some more required changes below:
2017-02-18 18_42_36-footprint editor no active library

For a more detailed explanation of the requirements. Please have a look at the reworked KLCs that we are currently preparing: https://github.com/SchrodingersGat/kicad-library/wiki/KLC
Also look at this set of scripts: https://github.com/KiCad/kicad-library-utils thats will help you check and autofix some of the KLC rules.

Best,
JAN

**Comment by jkriege2** [comment]
PS: Sorry, forgot to mention: the dark red (thick) line is the courtyard, as it should be later ... just drew it red, so it can be distinguished from the existing Courtyard.

For the pin1-mark, maybe use a double-line on the corner or something as here https://github.com/KiCad/Oscillators.pretty or here https://github.com/KiCad/Diodes_SMD.pretty. ... maybe it's also not SO important here, as the component may also be mounted, when rotated by 180°?

**Comment by MHolzbrecher** [comment]
Hi, 
fixed the KLC issues. Modified the pin-1 mark. It is not really important because it can be mounted rotated by 180°. But i think having a mark is better for clearness.

Michael

**Comment by jkriege2** [comment]
nice work!

Thanks,
JAN

**Pull request merged**
