### PR TITLE
TDK ACM1211 added

### PR DESCRIPTION
**Pull request by rtenhave**
common mode choke added from TDK (ACM1211)

### CODE REVIEW

**Comment by rtenhave** [comment]
violations are fixed

**Comment by jkriege2** [comment]
Hi!

nice work!

I only spotted two small problems:
1. please renmber pins so they conform to the symbol that we have:
2017-09-06 21_27_41-choose component 338 items loaded
2. Please add a link to the datasheet https://product.tdk.com/info/en/catalog/datasheets/cmf_commercial_power_acm1211_en.pdf to the description.

Best and Thanks,
JAN

PS: To help review process, please add a screenshot and a link to the dtaasheet this is based on to your PRs in future

**Comment by rtenhave** [comment]
Dear Jan,

Thank you for your response.
I understand that the CM symbol numbering is not compatible with the pin
numbering of my footprint. But according to the datasheet of the ACM1211
the numbering of my footprint correct.
So i think this is quite confusing.
Is it the policy of the KiCad footprint github that the numbering of the
symbols are leading?

Kind regards,

Roel ten Have

**Comment by Shackmeister** [comment]
@jkriege2 can you please comment on the questions above?

**Comment by poeschlr** [comment]
@rtenhave as the v5 release is slowly approaching we declare this repo as legacy.

If you are still interested in contributing please reopen this pull request over at the new repo.
https://github.com/KiCad/kicad-footprints

I am sorry that this creates more work for you.
all other inductor footprints have been moved in this pull request: https://github.com/KiCad/kicad-footprints/pull/3

**Pull request closed without merging**
