### PR TITLE
Added Sagami CER1257 & 1277 inductors

### PR DESCRIPTION
**Pull request by crackerizer**

### CODE REVIEW

**Comment by SchrodingersGat** [comment]
Hi @crackerizer can you please do the following:

a) Add the datasheet to all three sagami inductors `http://www.sagami-elec.co.jp/file/CER1242B-CER1257B-CER1277B.pdf`

b) For each inductor, please add the height to the `doc` field e.g. `h=6.0mm` (for easy differentiation as this is the only parameter difference as far as I can tell)

e.g. doc field - `Inductor, Sagami, h=6.0mm, http://www.sagami-elec.co.jp/file/CER1242B-CER1257B-CER1277B.pdf`

**Comment by crackerizer** [comment]
Hi, where should I add the datasheet to? the doc field?

**Comment by SchrodingersGat** [comment]
Yes just add it to the doc field like the example I gave above

**Comment by crackerizer** [comment]
Oh, ok, change has made.

**Pull request merged**
