### PR TITLE
Added Sagami CWR12XXC inductors

### PR DESCRIPTION
**Pull request by crackerizer**

### CODE REVIEW

**Comment by jkriege2** [comment]
Hi!

nice work. Please change some minor stuff:
1. make the silkscreen also alongside the beveled corners, so the orientation of the device is clear when putting it onto the PCB
2. the courtyard on left/right should be closer to the pads (0.25mm offset)

Best,
JAN

**Comment by jkriege2** [comment]
Hi!

sorry, it took a bit to come back to this ... This looks already very good. Only one minor thing remains to change: We need some  kind of pin1-marker, so you know how to mount the inductor. I would propose this (based on the DSs):
2017-03-08 21_03_16-footprint editor no active library

Best,
JAN

**Comment by SchrodingersGat** [comment]
@jkriege2 I don't think we need pin-1 indication for a non-polarized part... If this is the only objection you have, can we merge?

**Comment by jkriege2** [comment]
Problem is the orientation, as I pressume the two pin 1-1 and 2-2 are connected internally. Then rotating by 90° might short out the coil, if pads 1-1 and 2-2 are connected on the PCB, as then connection are coil-PCB:
1-1,1-2,2-2,2-1 (left->right)

**Comment by SchrodingersGat** [comment]
Oh, I see - is the silkscreen drawn above **your** suggestion? In that case it is a very good idea.

**Comment by jkriege2** [comment]
Yes that's my suggestion ;-)

**Comment by evanshultz** [comment]
@crackerizer Will you be able to make the simple change suggested above so this PR can be merged?

**Comment by evanshultz** [comment]
@crackerizer Are you willing to make the final update suggested above so this PR can be merged?

**Comment by evanshultz** [comment]
While the [datasheet](http://www.sagami-elec.co.jp/file/16Car_SMDCwr.pdf) doesn't seem contain the pinout, I was able to get this:
image

So it appears that there is in fact only one possible orientation for this coil. While the "bottom view" drawing shows wires Sagami says that only 2 pins are connected to the winding (and it can be installed at 0 or 180 degrees).

So... I propose the following to fix up this footprint:
- Add bevels to both the silk and fab layers in the corners where you marked above, Jan.
- Make the other corners go to a point, as opposed to the fab which has a bevel (it looks like glue there).
- Make the top and bottom pads have no number so they won't get a net connection.
- Mark in silk where the "Start side"/"Black like" would be to help the user during inductor installation.

**Comment by evanshultz** [comment]
I got more info from Sagami. The lines in section 3 of the Connection part of the datasheet are actually connected. So all 4 pins are an electrical connection to the inductor and there are 2 legitimate placements. However, since the part is marked with the black line our footprint should encourage placement in only one  orientation.

@crackerizer I'm going to take this PR since I haven't heard from you.

**Comment by evanshultz** [comment]
The connections are obvious once I searched for a [picture of the inductor](http://www.es.co.th/Picture/CWR-SAGAMI.jpg). You can see a metal band wrapping around the outside of the inductor connecting the left/bottom and the top/right pads.
image

**Comment by evanshultz** [comment]
With https://github.com/KiCad/Inductors_SMD.pretty/pull/13 being merged, I'm closing this PR.

**Pull request closed without merging**
