### PR TITLE
Add Sagami CWR series

### PR DESCRIPTION
**Pull request by evanshultz**
This is a fix of https://github.com/KiCad/Inductors_SMD.pretty/pull/10#event-1137251147.

Datasheet: http://www.sagami-elec.co.jp/file/16Car_SMDCwr.pdf

However, after contacting Sagami I was sent this more helpful page:
image

Image (same footprint but allowing different 3D models for height difference:
image

Changes from PR referenced above:
- Added 3D model
- Improved description and updated datasheet URL
- Swapped pin numbers of top and bottom pads
- Cleaned up and aligned all dimensions
- Changed inner F.Fab circle to 8.5mm diameter (per datasheet)
- Removed outer F.Fab circle
- Moved courtyard to 0.1mm grid
- Centered F.Fab ref des
- Added thick silk line to indicate inductor orientation
- Adjusted bevels so cross-body dimension is 15mm
- Add matching bevel in silkscreen
- Pushed silk slightly farther from pads (~0.1mm)

The only KLC error is the width of the silk line under the part to denote orientation. I figure there should be something to match up with the black line on the part, so I made a fat silk line. I can shrink the line width if this is a problem. Otherwise, for this part I don't think silk under it is an issue. But if you have some suggestions on a better way to mark orientation please let me know.

### CODE REVIEW

**Comment by SchrodingersGat** [comment]
The silkscreen looks different for the 1277C version - an oversight?

**Comment by evanshultz** [comment]
@SchrodingersGat Nope. An oversight on my part when I copied the silk changes from the 1277 to the other two, and missed a few lines. Fixed now. Thanks for checking.

**Comment by SchrodingersGat** [comment]
Thanks @evanshultz

**Comment by evanshultz** [comment]
If anyone wants to carry on with the rest of the CWR series, and is diligent to find this PR, here is some useful info.

The dimension diagonal across the inductor body is not shown on the datasheet. They are:
- CWR80: 10.1mm
- CWR10: 12.5mm
- CWR12: 15.0mm

In all cases, across the ferrite corners is +/-0.5mm tolerance while across the glue corners is +/-1.0mm.

That means for CWR12, breaking the part body across the diagonal into two triangles gives a triangle with a base of 7.5mm. Break that triangle into another pair of right-angled triangles, with a hypoteneuse of 7.5mm, and the sides will both be 5.3033mm. This is the X and Y dimension of the center point of the bevel. With that established, I simply needed to draw a 45 degree line with a center at (5.3,5.3) and touched the outer F.Fab lines. Voila!

A picture is probably easiest to understand:
image

**Pull request merged**
