### PR TITLE
Backslashes changed to forward slash

### PR DESCRIPTION
**Pull request by alitekin2fx**

### CODE REVIEW

**Comment by Shackmeister** [comment]
Thank you, Nicely spotted :)

**Comment by alitekin2fx** [comment]
Hi  @Shackmeister, i think there is also missing labels on fabrication layer. I'll try to update it also.

**Comment by Shackmeister** [comment]
There is indeed, it would be very nice if you can fix it :) please don't hesitate to ask if you have problems

**Comment by alitekin2fx** [comment]
Yes, do you have any script to add %R label to fabrication layer :)

**Comment by Shackmeister** [comment]
Sure :) here is a PR where I asked the exact same question :) https://github.com/KiCad/Capacitors_THT.pretty/pull/15 but remember to manually check what the script spits out. :)

**Comment by alitekin2fx** [comment]
Thank you @Shackmeister.

**Pull request merged**
