### PR TITLE
addind 5030 & 8040 footprint

### PR DESCRIPTION
**Pull request by jeromebeguin**
from previous Inductor library.

### CODE REVIEW

**Comment by jkriege2** [comment]
1.`L_5030` shouldn't the pads be arrange more like in this document: https://product.tdk.com/info/en/catalog/datasheets/inductor_commercial_power_spm5030_en.pdf ? Could you give a datasheet for comparison/evaluation? Thanks!
2. I think `L_8040` should be renamed to `L_TDK_VLP8040` 
3.`L_5030` please set attribute to SMD
4. please make silkscreen lines 0.12mm thick, courtyards 0.05mm thick and F.Fab 0.1mm

Thanks!
JAN

**Comment by jeromebeguin** [comment]
1. here is the datasheet I used for the L_5030 footprint: [XAL50XX](http://www.mouser.com/ds/2/597/xal50xx-270657.pdf)

I did the other modifications. 

Best
Jerome

**Comment by jkriege2** [comment]
1. OK, please rename `L_5030' to `L_Coilcraft_XAL5030`
2. top-left-corner lines on TDK-inductor are 0.12mm thick, but should be 0.1mm

Best,
JAN

**Comment by jkriege2** [comment]
nice work!

JAN

**Pull request merged**
